function r=defineRegisters
  %% Experiment configuration
  r.RAM_SIZE=200;
  r.EEPROM_SIZE=32;
  
  r.EEPROM_DYN_SLAVE_BASE_ADDRESS1=uint16(hex2dec('0000'));
  r.EEPROM_DYN_SLAVE_BASE_ADDRESS2=uint16(hex2dec('0010'));
  
  r.DEFAULT_DEVICE_MODEL=uint16(hex2dec('7300'));
  r.DEFAULT_FIRMWARE_VERSION=uint16(hex2dec('0001')); 
  r.DEFAULT_DEVICE_ID=uint16(hex2dec('0001'));
  r.DEFAULT_BAUDRATE=uint16(hex2dec('0010'));
  r.DEFAULT_RETURN_DELAY=uint16(hex2dec('0000'));
  r.DEFAULT_RETURN_LEVEL=uint16(hex2dec('0002'));  
  
  r.MAX_DYN_SLAVE_TX_BUFFER_LEN=1024;
  r.MAX_DYN_SLAVE_RX_BUFFER_LEN=1024;
  r.MAX_DYN_SLAVE_REG_BUFFER_LEN=1024;
  
  r.MAX_NUM_BUFFERS=8;
  r.MAX_BUFFER_LEN=(2*1024);
  
  r.DEFAULT_NOISE_GEN_SAMPLING_RATE=10000;
  r.DEFAULT_NOISE_GEN_DAC_VCC=3300;
  
  r.MAX_NUM_EVENTS=16;
  r.MAX_NUM_ACTIONS=4;

  %% Cam triggers
  r.RAM_CAM_TRIG_BASE_ADDRESS=uint16(hex2dec('0041'));
  r.CAM_TRIG_CONTROL=r.RAM_CAM_TRIG_BASE_ADDRESS;
  r.CAM_TRIG_START=uint8(hex2dec('01'));
  r.CAM_TRIG_STOP =uint8(hex2dec('02'));
  r.CAM_TRIGGERED=uint8(hex2dec('80'));
  
  %% Actions
  r.ACTION_ID_MASK = uint32(hex2dec('F0000000'));
  r.ACTION_PARAMS_MASK = uint32(hex2dec('0FFFFFFF'));
  
  r.NOISE_START=uint32(hex2dec('10000000'));
  r.NOISE_STOP=uint32(hex2dec('20000000'));
  r.NOISE_BUFFER=uint32(hex2dec('000000FF'));
  
  r.CAMERA_START=uint32(hex2dec('30000000'));
  r.CAMERA_STOP=uint32(hex2dec('40000000'));
  
  r.LIGHT_START=uint32(hex2dec('50000000'));
  r.LIGHT_STOP=uint32(hex2dec('60000000'));
  r.LIGHT_DUTY=uint32(hex2dec('000000FF'));
 
  %% Events
  r.RAM_EVENTS_BASE_ADDRESS=uint16(hex2dec('0029')); 
  r.RAM_EVENTS_LENGTH=8+r.MAX_NUM_EVENTS;
  r.EVENTS_CONTROL=r.RAM_EVENTS_BASE_ADDRESS;
  r.EVENTS_ADD_EVENT=uint8(hex2dec('01'));
  r.EVENTS_REMOVE_EVENT=uint8(hex2dec('02'));
  r.EVENTS_ADD_ACTION=uint8(hex2dec('04'));
  r.EVENTS_REMOVE_ACTION=uint8(hex2dec('08'));
  r.EVENTS_START=uint8(hex2dec('10'));
  r.EVENTS_STOP=uint8(hex2dec('20'));
  r.EVENTS_CLEAR_ALL=uint8(hex2dec('40'));
  r.EVENTS_RUNNING=uint8(hex2dec('80'));
  r.EVENTS_NUM_EVENTS=r.RAM_EVENTS_BASE_ADDRESS+1;
  r.EVENTS_NUM_ACTIONS=(r.RAM_EVENTS_BASE_ADDRESS+2);
  r.EVENTS_EVENT_ID=(r.RAM_EVENTS_BASE_ADDRESS+2+r.MAX_NUM_EVENTS);
  r.EVENTS_ACTION_ID=(r.RAM_EVENTS_BASE_ADDRESS+3+r.MAX_NUM_EVENTS);
  r.EVENTS_DATA=(r.RAM_EVENTS_BASE_ADDRESS+4+r.MAX_NUM_EVENTS);

  %% Ligth
  r.RAM_LIGHT_BASE_ADDRESS=uint16(hex2dec('0042'));
  r.RAM_LIGHT_LENGTH=2;
  r.LIGHT_CONTROL=(r.RAM_LIGHT_BASE_ADDRESS);
  r.LIGHT_START_DUTY=uint8(hex2dec('01'));
  r.LIGHT_STOP_DUTY=uint8(hex2dec('02'));
  r.LIGHT_ON=uint8(hex2dec('80'));
  r.LIGHT_DUTY_CYCLE=(r.RAM_LIGHT_BASE_ADDRESS+1);

  %% Noise generation
  r.RAM_NOISE_GEN_BASE_ADDRESS=uint16(hex2dec('0020'));
  r.RAM_NOISE_GEN_LENGTH=9;
  r.NOISE_GEN_CONTROL=(r.RAM_NOISE_GEN_BASE_ADDRESS);
  r.NOISE_GEN_ADD_BUFFER=uint8(hex2dec('01'));
  r.NOISE_GEN_REMOVE_BUFFER=uint8(hex2dec('02'));
  r.NOISE_GEN_START=uint8(hex2dec('04'));
  r.NOISE_GEN_STOP=uint8(hex2dec('08'));
  r.NOISE_GEN_CLEAR=uint8(hex2dec('10'));
  r.NOISE_GEN_RUNNING=uint8(hex2dec('80'));
  r.NOISE_GEN_NUM_BUFFERS=(r.RAM_NOISE_GEN_BASE_ADDRESS+1);
  r.NOISE_GEN_FREQ=(r.RAM_NOISE_GEN_BASE_ADDRESS+2);
  r.NOISE_GEN_AMPLITUDE=(r.RAM_NOISE_GEN_BASE_ADDRESS+4);
  r.NOISE_GEN_OFFSET=(r.RAM_NOISE_GEN_BASE_ADDRESS+6);
  r.NOISE_GEN_BUFFER_ID=(r.RAM_NOISE_GEN_BASE_ADDRESS+8);
  r.EEPROM_NOISE_GEN_BASE_ADDRESS=uint16(hex2dec('0011'));
  r.EEPROM_NOISE_GEN_LENGTH=4;
  r.NOISE_GEN_SAMPLING_FREQ=(r.EEPROM_NOISE_GEN_BASE_ADDRESS);
  r.NOISE_GEN_DAC_VCC=(r.EEPROM_NOISE_GEN_BASE_ADDRESS+2);
  r.DEFAULT_NOISE_GEN_SAMPLING_RATE=10000;
  r.DEFAULT_NOISE_GEN_DAC_VCC=3300;

end
  
